public with sharing class B2B_SetupConstants {
    public static final String HTTP_CONTENT_APP_JSON = 'application/json';
    public static final String HTTP_REQUEST_PATCH = 'PATCH';
    public static final String HTTP_REQUEST_GET = 'GET';
    public static final String HTTP_CONTENT_TYPE = 'Content-Type';
    public static final String HTTP_AUTHORIZATION_HEADER = 'Authorization';
    public static final String IS_REQUEST_SUCCESS ='isRequestSuccess';
    public static final String HTTP_SERVICE_APEX_REST = '/services/apexrest';
    public static final String PRODUCTID = 'ProductId';
    public static final String PRODUCTSKU = 'productSku';
    public static final String QUANTITY = 'quantity';
    public static final String CART_ID = 'cartId';
    public static final String CASE_OBJ = 'caseObj';
}
